<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>OrcaCore.Provider.Abstractions</AssemblyName>
    <PackageId>OrcaCore.Provider.Abstractions</PackageId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\OrcaCore.Abstractions\OrcaCore.csproj" />
    <ProjectReference Include="..\OrcaCore.Runtime.Protocol\OrcaCore.Runtime.Protocol.csproj" />
  </ItemGroup>
</Project>
