<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../../../../../src/OrcaCore.Abstractions/OrcaCore.Abstractions.csproj" />
    <ProjectReference Include="../../../../../src/OrcaCore.Core/OrcaCore.Core.csproj" />
    <ProjectReference Include="../../../../../src/OrcaCore.Engine.Durable/OrcaCore.Engine.Durable.csproj" />
    <ProjectReference Include="../../../../../src/OrcaCore.Providers.InMemory/OrcaCore.Providers.InMemory.csproj" />
    <ProjectReference Include="../../../../../src/OrcaCore.Hosting/OrcaCore.Hosting.csproj" />
  </ItemGroup>
</Project>
