<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><PackageReference Include="OrcaCore" /><PackageReference Include="OrcaCore.Dag" /><PackageReference Include="OrcaCore.Dag.Hosting" /><PackageReference Include="OrcaCore.Durable.Hosting" /><PackageReference Include="OrcaCore.Providers.InMemory" /></ItemGroup></Project>
