<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../OrcaCore.DeveloperSurface.BehaviorContracts/OrcaCore.DeveloperSurface.BehaviorContracts.csproj" />
    <ProjectReference Include="../../src/OrcaCore.Abstractions/OrcaCore.csproj" />
    <ProjectReference Include="../../src/OrcaCore.Core/OrcaCore.Core.csproj" />
    <ProjectReference Include="../../src/OrcaCore.Engine.Durable/OrcaCore.Engine.Durable.csproj" />
    <ProjectReference Include="../../src/OrcaCore.Durable.Hosting/OrcaCore.Durable.Hosting.csproj" />
    <ProjectReference Include="../../src/OrcaCore.Engine.Ephemeral/OrcaCore.Engine.Ephemeral.csproj" />
    <ProjectReference Include="../../src/OrcaCore.Providers.InMemory/OrcaCore.Providers.InMemory.csproj" />
    <ProjectReference Include="../../src/OrcaCore.Providers.PostgreSql/OrcaCore.Providers.PostgreSql.csproj" />
    <ProjectReference Include="../../src/OrcaCore.Dag.Hosting/OrcaCore.Dag.Hosting.csproj" />
  </ItemGroup>
</Project>
