using System.Text.Json;
using System.Text.Json.Serialization;
using OrcaCore.Abstractions.Durable;
using OrcaCore.Abstractions.Providers;

namespace OrcaCore.Abstractions.Serialization;

[JsonSourceGenerationOptions(JsonSerializerDefaults.Web)]
[JsonSerializable(typeof(WorkflowStartedEvent))]
[JsonSerializable(typeof(WorkflowContinuedAsNewEvent))]
[JsonSerializable(typeof(WorkflowStepCompletedEvent))]
[JsonSerializable(typeof(WorkflowStepFailedEvent))]
[JsonSerializable(typeof(WorkflowWaitRegisteredEvent))]
[JsonSerializable(typeof(WorkflowWaitMatchedEvent))]
[JsonSerializable(typeof(WorkflowTimerScheduledEvent))]
[JsonSerializable(typeof(WorkflowTimerFiredEvent))]
[JsonSerializable(typeof(WorkflowChildScheduledEvent))]
[JsonSerializable(typeof(WorkflowChildrenScheduledEvent))]
[JsonSerializable(typeof(WorkflowChildrenDispatchedEvent))]
[JsonSerializable(typeof(WorkflowChildCompletedEvent))]
[JsonSerializable(typeof(WorkflowParentResumeTokenRecordedEvent))]
[JsonSerializable(typeof(WorkflowParentResumeTokenConsumedEvent))]
[JsonSerializable(typeof(WorkflowChildResidualIntentRecordedEvent))]
[JsonSerializable(typeof(WorkflowChildCompensationScheduledEvent))]
[JsonSerializable(typeof(WorkflowResourcePoolAcquiredEvent))]
[JsonSerializable(typeof(WorkflowResourcePoolQueuedEvent))]
[JsonSerializable(typeof(WorkflowResourcePoolReleasedEvent))]
[JsonSerializable(typeof(WorkflowExternalJobStartedEvent))]
[JsonSerializable(typeof(WorkflowExternalJobCompletedEvent))]
[JsonSerializable(typeof(WorkflowExternalJobTimedOutEvent))]
[JsonSerializable(typeof(WorkflowExternalJobStopRequestedEvent))]
[JsonSerializable(typeof(WorkflowTimerBufferedEvent))]
[JsonSerializable(typeof(WorkflowPausedEvent))]
[JsonSerializable(typeof(WorkflowResumedEvent))]
[JsonSerializable(typeof(WorkflowDeliveryBufferedEvent))]
[JsonSerializable(typeof(WorkflowDeliveryDiscardedEvent))]
[JsonSerializable(typeof(WorkflowCompletedEvent))]
[JsonSerializable(typeof(WorkflowTerminalEvent))]
[JsonSerializable(typeof(SagaForwardActionCompletedEvent))]
[JsonSerializable(typeof(SagaForwardActionTimedOutEvent))]
[JsonSerializable(typeof(SagaCompensationRequestedEvent))]
[JsonSerializable(typeof(SagaCompensationStartedEvent))]
[JsonSerializable(typeof(SagaCompensationCompletedEvent))]
[JsonSerializable(typeof(SagaCompensationFailedEvent))]
[JsonSerializable(typeof(SagaManualRecoveryRecordedEvent))]
[JsonSerializable(typeof(WorkflowRuntimeCheckpointState))]
public sealed partial class OrcaCoreJsonSerializerContext : JsonSerializerContext;
