<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\OrcaCore.Core\OrcaCore.Core.csproj" />
    <ProjectReference Include="..\OrcaCore.Abstractions\OrcaCore.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="OrcaCore.Engine.Ephemeral.Tests" />
  </ItemGroup>

</Project>
