<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\OrcaCore.Abstractions\OrcaCore.Abstractions.csproj" />
    <ProjectReference Include="..\OrcaCore.Core\OrcaCore.Core.csproj" />
    <ProjectReference Include="..\OrcaCore.Engine.Ephemeral\OrcaCore.Engine.Ephemeral.csproj" />
    <ProjectReference Include="..\OrcaCore.Engine.Durable\OrcaCore.Engine.Durable.csproj" />
    <ProjectReference Include="..\OrcaCore.Providers.InMemory\OrcaCore.Providers.InMemory.csproj" />
  </ItemGroup>

</Project>
