<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="BrokerAdapters\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\OrcaCore.Abstractions\OrcaCore.csproj" />
    <ProjectReference Include="..\..\src\OrcaCore.Durable.Hosting\OrcaCore.Durable.Hosting.csproj" />
    <ProjectReference Include="..\..\src\OrcaCore.Providers.InMemory\OrcaCore.Providers.InMemory.csproj" />
  </ItemGroup>
</Project>
